version: '3.8'

services:
  #  postgres:
  #    container_name: postgres
  #    image: postgres:13
  #    volumes:
  #      - postgresVolume:/var/lib/postgresql/data
  #    environment:
  #      POSTGRES_USER: postgres
  #      POSTGRES_PASSWORD: postgres
  #    ports:
  #      - 5432:5432
  #    networks:
  #      - amalaNetwork

  mongodb:
    container_name: mongodb
    image: mongo:6.0.5-jammy
    volumes:
      - mongoVolume:/data/db
    environment:
      MONGO_USER: mongo
      MONGO_PASSWORD: mongo
    ports:
      - '27017:27017'
    networks:
      - amalaNetwork

  #  redis:
  #    container_name: redis
  #    image: redis:6-alpine
  #    volumes:
  #      - redisVolume:/data
  #    ports:
  #      - 6379:6379
  #    networks:
  #      - amalaNetwork

  api:
    container_name: api
    restart: always
    #    depends_on:
    #      - mongodb
    #      - postgres
    #      - redis
    build:
      context: .
      target: devDependencies
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    environment:
      #      - REDIS_HOST=redis
      - MONGO_HOST=mongodb
    #      - POSTGRES_HOST=postgres
    volumes:
      - .:/home/node/app
      # Uncomment the below line if you developing on MacOS
      - /home/node/app/node_modules
    working_dir: /home/node/app
    command: npm run dev --watch --node-args="--inspect=0.0.0.0"
    networks:
      - amalaNetwork

volumes:
  #  postgresVolume:
  #  redisVolume:
  mongoVolume:

networks:
  amalaNetwork:
    driver: bridge
